"""empty message

Revision ID: 42f52f21b854
Revises: 1be4f3cab7a6
Create Date: 2017-05-10 14:03:01.488868

"""

# revision identifiers, used by Alembic.
revision = '42f52f21b854'
down_revision = '1be4f3cab7a6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
